### ISSUE TITLE
RaspiAPA102DeviceInitSoftware

### ISSUE THREAD

**Issue by x893** [flobernd/raspi-apa102#1]
if (pin_cs >= 0)
    {
        pinMode(pin_cs, OUTPUT);
        digitalWrite(device->pin_sclk, HIGH);
    }
May be
        digitalWrite(device->**pin_cs**, HIGH);

**Comment by flobernd** [comment]
You are correct! Do you want to submit a PR or may I change it for you?

**Comment by x893** [comment]
FYI (No PR), make changes as you wants.

**Comment by flobernd** [comment]
Thanks for reporting! Fixed.
